### ISSUE TITLE
test

### ISSUE THREAD

**Issue by philliptracy** [ORCID/i2-workshop-2016#9]

**Comment by orcid-devsupport** [comment]
Thank you for contacting ORCID.

Our support hours are Monday through Friday, with limited weekend
support for emergencies, such as security incidents.

If it is the weekend and you need to report an emergency, please
resend your email with the word URGENT in the subject line. We
shall respond within 24 hours if it is a critical issue.

We also invite you to visit our Knowledge Base to find answers to
the most commonly asked questions about ORCID and managing your
ORCID record: http://support.orcid.org ( http://support.orcid.org )

Warm regards,

ORCID Community Team

On April 22, 2017 at 1:52 AM ORCID/i2-workshop-2016 wrote:

--

You are receiving this because you are subscribed to this thread.

Reply to this email directly or view it on GitHub:

https://github.com/ORCID/i2-workshop-2016/issues/9 ( https://github.com/ORCID/i2-workshop-2016/issues/9 )
